title: Aditya Chaudhari
author: Aditya Chaudhari

header_pages:
  - index.md
  - about.md

style: dark
listen_for_clients_preferred_style: true

footer: 'footer <a href="https://google.com">google</a>'

remote_theme: b2a3e8/jekyll-theme-console
